name: CivvieCore
version: '${project.version}'
main: me.zombie_striker.civviecore.CivvieCorePlugin
api-version: 1.19
authors: [ Zombie_Striker ]
softdepend:
  - 'Terra'
commands:
  reinforce:
    aliases: ['r']
    description: 'Reinforces a block'
  nl:
    description: 'Used for all namelayer features'
  nlc:
    aliases: ['nlcreate']
    description: 'Used to create namelayers'
  fm:
    aliases: ['factorymod']
    description: 'Used to see recipes for factory mod.'
  g:
    aliases: ['global']
    description: 'Used for chat.'
  ep:
    aliases: ['enderpearl']
    description: 'Used for enderpearl commands.'
  nlaccept:
    aliases: ['nla']
    description: 'Used to accept Name Layer Invites.'
